CONTAINER TAeroplane
{
	NAME TAeroplane;
    INCLUDE Texpression;
    
    GROUP ID_TAGPROPERTIES
	{
		BOOL AEROPLANE_ENABLED { }

		LINK AEROPLANE_LINK
		{
			ACCEPT { Oplane; }
		}

		BOOL AEROPLANE_SAVED 		{ HIDDEN; }
		VECTOR AEROPLANE_CAM_ROT	{ HIDDEN; }
		REAL AEROPLANE_CAM_FOV		{ HIDDEN; }
		REAL AEROPLANE_CAM_OFFX		{ HIDDEN; }
		REAL AEROPLANE_CAM_OFFY		{ HIDDEN; }
		BOOL AEROPLANE_PLANE_XRAY	{ HIDDEN; }
	}
}
